### PR TITLE
Add includedir to pkgconfig and taglib-config so that #include <taglib/t...

### PR DESCRIPTION
**Pull request by dfaure**
...ag.h> works.

### CODE REVIEW

**Comment by dfaure** [comment]
ping?

**Comment by lalinsky** [comment]
Sorry for the delay. The <taglib/foo.h> include is not really supposed to work. I don't mind changing it in TagLib 2.0 (possibly with keeping the whole structure, not flattening the sub-directories), but I'm not sure if this is a good idea for master.

**Comment by dfaure** [comment]
This is an invasion of the global namespace :-)

#include <tag.h> in any application could be ambiguous, if the application (or some other library invading the global namespace) has a file called tag.h.
It would be much cleaner to be able to use #include <taglib/tag.h>.
Many people are already doing that since it works in a standard distro install where this is in /usr/include/taglib/tag.h
It just breaks in different setups where taglib is installed elsewhere.

People have been trying to work around that breakage by different means:
https://git.reviewboard.kde.org/r/120244/
https://projects.kde.org/projects/extragear/multimedia/plasma-mediacenter/repository/revision?rev=e449b1bcc54dfa3ee3b684f666fdae98a8468617
https://projects.kde.org/projects/extragear/multimedia/plasma-mediacenter/repository/revision?rev=8fba0e62df2277bc23cb4bfa28711c22b33ac78e

This is all quite a mess, because everyone agrees that <taglib/tag.h> is the right way, but it doesn't actually work that way for everyone compiling the code. This commit fixes that.

I can't comment on master vs 2.0, I don't know the branching structure for taglib.
But my commit preserves source compatibility, so I don't see an issue with committing it in "whatever is released next". Code using <tag.h> will still work.

**Comment by dfaure-kdab** [comment]
ping?

**Comment by lalinsky** [comment]
As I said, I really do not want to change this in master and I did not get any other opinions on this. I fully realize that it is an invasion of the global namespace, but it has been like that for years.

**Comment by mkae** [comment]
I am in favour of this change, since avoiding global namespace invasion is the way to go.

**Comment by gogglesguy** [comment]
Given its source compatibility I don't see a need to delay this until 2.0. Who knows when that may be ever released. Then again, kde has been polluting my /usr/include directory for years, so it's a bit funny to see that coming from kde.org...

**Comment by dfaure-kdab** [comment]
gogglesguy: that "pollution" was at least k-prefixed, so not as bad as "tag.h", and is fixed with KDE Frameworks 5.

**Pull request closed without merging**
