### PR TITLE
Silence uint ambiguity errors in tests.

### PR DESCRIPTION
**Pull request by FestusHagen**
FreeBSD-8.2 (GCC 4.2.1) errors with uint ambiguity ...

### CODE REVIEW

**Comment by scotchi** [comment]
I'd prefer to not hit existing code with astyle until we hit all of it with astyle.  It'll be a massive change, and I'd like to minimize the damage to the repository's history.

**Comment by FestusHagen** [comment]
Yes sir ... Not sure how without closing/re-requesting, But I will see if I can figure it out ASAP!

rebase is a command I've stayed away from.

I would welcome tips on the preferred technique. Anyone?

Thank you for letting me know!

**Comment by TsudaKageyu** [comment]
I think I can merge this now, since it only covers the tests.

**Comment by FestusHagen** [comment]
Thank you, it's been a thorn in my side ... having to patch to test reduces confidence in the base code!

**Comment by TsudaKageyu** [comment]
Well, I added several tests after you created this PR.
Are those tests compatible with your compiler?

**Comment by FestusHagen** [comment]
Current master builds and passes all tests with MinGW-4.9.1 as of 13dab99.

The last time I tested with FreeBSD or OSX was at e90b5e5, they are currently busy building other software. I should be able to test with them by tomorrow am.
-Enjoy

**Pull request merged**
