### PR TITLE
Stop calculating the offset in RIFF::File::chunkData().

### PR DESCRIPTION
**Pull request by TsudaKageyu**

### CODE REVIEW

**Comment by sbooth** [comment]
This looks good to me but I'd like for @lalinsky or @scotchi to weigh in before I merge the PR.  It appears that `offset` is calculated when the chunk is read so the code is equivalent but I'm wondering if there is a reason it wasn't written this way initially.

**Comment by TsudaKageyu** [comment]
Yes, I think so.

**Comment by TsudaKageyu** [comment]
Non-urgent. Close for now.

**Comment by TsudaKageyu** [comment]
I checked the history of ```rifffile.cpp``` again. And I now think it's just an omission in  a2aaf8a8e17372caef3388cb06a88d65f7be52ea.

**Pull request merged**
