### PR TITLE
Avoid memmove across different buffers in ByteVector::replace()

### PR DESCRIPTION
**Pull request by TsudaKageyu**
detach() is called inside ByteVector::data().

### CODE REVIEW

**Comment by lalinsky** [comment]
Can you please explain why this is not necessary?

**Comment by TsudaKageyu** [comment]
Non-const version of ```ByteVector::data()``` calls ```detach()``` internally and the first parameter of ```memmove()/memcpy()``` is non-const.

**Comment by lalinsky** [comment]
I don't think that the code with `memmove()` is correct like this. For example, the first `data()` call returns the current pointer because there is only one reference, then some other thread adds a reference, so the second `data()` call has to actually detach and it returns a different pointer. Now you are moving across two different data pointers.

**Comment by TsudaKageyu** [comment]
Hmm, but I think calling ```detach()``` first won't solve it. We have to do, for example, like this.
```
    if(diff < 0) {
      char *p = data();
      ::memmove(
        p + offset + withSize,
        p + offset + patternSize,
        size() - offset - patternSize);
      resize(size() + diff);
    }
    else if(diff > 0) {
      resize(size() + diff);
      char *p = data();
      ::memmove(
        p + offset + withSize,
        p + offset + patternSize,
        size() - diff - offset - patternSize);
    }
```

**Comment by lalinsky** [comment]
Well, the first detach makes sure there is only one reference and no other code knows about the newly created reference, so currently it should work, but it's not very clear.

**Comment by TsudaKageyu** [comment]
I think the new change makes things a bit clearer.

**Comment by gogglesguy** [comment]
I guess all bets are off when you're talking multithreaded. In the single threaded case, just a single call to detach outside the loop would have been sufficient. I believe TsudaKageyu is correct: the detach() won't work if another thread comes by and references this vector again. However, I'd be really afraid if this would actually happen, since after all we're in the middle of modifying this vector. Are we aiming for a complete multithread safe bytevector?

Anyway, the new changes look fine to me.

**Pull request closed without merging**
