### PR TITLE
mp4 properties: handle the case when mp4 file header has zero bitrate

### PR DESCRIPTION
**Pull request by shaforostoff**
calculate it based on filesize and length

i can send you the link to the broken file, if you like

### CODE REVIEW

**Comment by sbooth** [comment]
Could you send me the link to the broken file?

**Comment by shaforostoff** [comment]
hey, i did send you the link. did you get it?

**Comment by scotchi** [comment]
Do you happen to know what created these files with broken headers?  Unless it's something very common, my impulse is not to work around this sort of brokenness.

**Comment by ufleisch** [comment]
The calculated bitrate seems to be slightly too high, so I suggest that we incorporate this patch into #981 and use the same calculation:

```
        if(data.toUInt(pos) != 0u || d->length <= 0) {
          d->bitrate = static_cast<int>((data.toUInt(pos) + 500) / 1000.0 + 0.5);
        }
        else {
          d->bitrate = static_cast<int>((calculateMdatLength(atoms->atoms) * 8) / d->length);
        }
```

**Comment by ufleisch** [comment]
Is merged with #981.

**Pull request closed without merging**
