### PR TITLE
Support the audio length in milliseconds

### PR DESCRIPTION
**Pull request by TsudaKageyu**
This patch enables TagLib to return the length of audio in milliseconds in addition to seconds.

As suggested in #503, it adds an abstract function like this to ```AudioProperties``` and its derived classes.
```
    /*!
     * Returns the length of the file in milliseconds.
     */
    virtual int lengthInMilliseconds() const = 0;
```
This also enables to calculate the actual average bitrate of Vorbis/Speex files and removes some useless data members from ```AudioProperties``` related classes.

### CODE REVIEW

**Comment by scotchi** [comment]
This could only be added to the taglib2 branch since it breaks binary compatibility.

**Comment by DidierMalenfant** [comment]
Maybe we could add one for 1.9.x that only adds the new property?

**Comment by TsudaKageyu** [comment]
Oh! I forgot that adding a virtual function breaks the ABI...
Though it's a little inconvenient, change ```lengthInMilliseconds()``` to non-virtual will fix the problem. Is it OK?

**Comment by TsudaKageyu** [comment]
I confirmed that ABI compliance checker doesn't report any errors now.

**Comment by TsudaKageyu** [comment]
Added support for VBRI headers of MPEG files.

```MPEG::XingHeader``` now supports VBRI headers in addition to Xing headers. It's a little weird, but I couldn't change the name due to ABI compatibility, and hesitant to add a new ```VBRIHeader``` class because it would be almost the same as ```XingHeader```.

**Comment by TsudaKageyu** [comment]
This also fixes the bug reported in #520.

**Comment by scotchi** [comment]
I was just thinking about this now, and I kind of like the idea of specifying a unit a bit more -- what do others think about this?

    enum TimeUnit
    {
      Seconds,
      Milliseconds
    };

    int AudioProperties::length(TimeUnit unit = Seconds) const

This doesn't affect the binary compatibility stuff (it'd actually need to be added without the default argument and then merged in 2.x), but I kind of like the look of that a bit better.

**Comment by DidierMalenfant** [comment]
I'm a big proponent of documenting the code with the code itself instead of comments so this is definitely a good idea in my opinion.

Any reason for using an argument as opposed to creating seperate methods?
````
   int AudioProperties::lengthInSeconds() const
   int AudioProperties::lengthInMilliSeconds() const
````
It reads better and would be slightly more efficient.

If anything, the enum values could be at least made to be ````InSeconds```` and ````InMilliseconds```` again for readability.

**Comment by scotchi** [comment]
I think I'd be fine with that option too -- and deprecating `length()`.  My issue at the moment is that I don't like the inconsistency that `length()` and `lengthInMilliseconds()` introduces in the naming.

**Comment by TsudaKageyu** [comment]
I agree. It's fine to do both -- clarify the meaning of the functions and straighten out the inconsistency.

**Comment by lalinsky** [comment]
I personally prefer the option with deprecating `length()` and adding `lengthInSeconds() ` and `lengthInMilliSeconds()`.

**Comment by TsudaKageyu** [comment]
I prefer it too. I will implement the changes soon.

**Comment by gogglesguy** [comment]
:-1: 

Keep it simple please. Just offer the length in milliseconds only. Why bloat the library with two functions that essentially just give you the same information. And not it's not like as if writing length() / 1000 in the client code is rocket science. And the solution for 1.9.x is even more horrible, having to repeat the lengthInSeconds() in every subclass, while having to keep the deprecated length() as well.

**Comment by TsudaKageyu** [comment]
I see your points. However, it comes from the discussion above.
We can neither remove existing functions and add virtual functions due to binary compatibility.

**Comment by scotchi** [comment]
Also, I think in TagLib 2.x having a function with the same signature but that returns different values would be sub-optimal.

**Comment by TsudaKageyu** [comment]
I am self-reviewing this PR, and I now find it too huge for us to make a thorough review.
So I am thinking of dividing this one into each audio format.

Any thoughts?

**Comment by sbooth** [comment]
That's a good idea, it would definitely simplify the review process.

**Comment by TsudaKageyu** [comment]
Thanks @sbooth, so could you please merge #484?
It will help me improve some audio property implementations and fix #482.

**Comment by sbooth** [comment]
Merged, sorry for the delay.

**Comment by TsudaKageyu** [comment]
No problem, thanks!

**Pull request closed without merging**
