### PR TITLE
Add CMake option for building with zlib

### PR DESCRIPTION
**Pull request by JuliusBrueggemann**
Since zlib is an optional dependency, it should be possible to build taglib without it, even if zlib is installed. Currently, this is not possible. This PR aims to change that by adding a CMake option `USE_ZLIB`.

### CODE REVIEW

**Comment by ufleisch** [comment]
Please squash your two commits. I personally think that `WITH_` is more commonly used than `USE_`, so I would have `WITH_ZLIB` instead of `USE_ZLIB` (but maybe this is a leftover from the good? old autotools days). It would also be good to see some documentation about this option in INSTALL.md.

**Comment by JuliusBrueggemann** [comment]
I don't have any preference regarding `USE_` vs `WITH_`, so I changed that to `WITH_ZLIB`.

I also squashed my commits and added a quick note about the option in the INSTALL.md

**Comment by ufleisch** [comment]
Looks good, I just replaced "wheter" by "whether".

**Comment by JuliusBrueggemann** [comment]
Oh, how embarrassing 😅 . Thank you.

**Pull request merged**
