### PR TITLE
Fix warnings issued by MSVC (#1185)

### PR DESCRIPTION
**Pull request by ufleisch**
I do not like the many `TAGLIB_EXPORT` line introduced here either, but it is probably still better than forcing MSVC users to disable warnings. An alternative would be not to use `std::unique_ptr`.

Unfortunately, MSVC exports everything (not only public members) when `__declspec(dllexport)` is set at the class level via `TAGLIB_EXPORT`, which leads to many "needs to have dll-interface to be used by clients" 4251 warnings issued by MSVC, because the `std::unique_ptr` pimpls are exported too. As it is not possible to "unexport" private members, all public and protected class member now have to be exported. The MP4 atom classes have to be refactored to use private implementation classes and a few other warnings had to be fixed. Now MSVC compiles the code without warnings, and there is only a single suppression in _tpropertymap.cpp_ because the case for exported template instantiations does not seem to be solvable.

Also remove deprecated functions:
- `APE::Item::value()`: use `binaryData()`
- `APE::Item::toStringList()`: use `values()`
- `MPEG::ID3v2::Frame::Header::unsycronisation()`: use `unsynchronisation()`

### CODE REVIEW

**Comment by sbooth** [comment]
I'm not a user of MSVC so I can't really test this idea, but would creating a `.DEF` file be an alternative to these changes? I don't think the public API changes often enough that a `.DEF` file would be unmanageable to keep updated once created.

**Comment by ufleisch** [comment]
I only use this compiler when I have to. I am therefore reluctant to deface all headers or manage .DEF files because of it. I have now cleaned up the changes into separate commits and reduced the changes to keep exporting the whole class and explicitly suppress the MSVC warning for STL private members, this should be OK since they are not accessible for clients. I have only switched to exporting individual members where it is needed, i.e. for classes deriving from templates (`StringList, ByteVectorList, PropertyMap`).

**Comment by sbooth** [comment]
Too bad not supporting MSVC isn't an option 😆

**Comment by sbooth** [comment]
In all seriousness though I think these changes are an excellent improvement.

**Review by neheb — APPROVED** [review]

**Comment by neheb** [comment]
wonder if clang on Windows behaves differently.

**Comment by ufleisch** [comment]
> wonder if clang on Windows behaves differently.

I have tested it with MSYS Clang, it builds without warnings.

**Comment by neheb** [comment]
> > wonder if clang on Windows behaves differently.
> 
> I have tested it with MSYS Clang, it builds without warnings.

I meant clang-cl or Clang on Windows, not MSYS2.

**Pull request merged**
