### PR TITLE
use using declarations

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by ufleisch** [comment]
Is there a reason why these `using` declarations are not below `public:`? Both seems to work, is there a difference?

**Comment by neheb** [comment]
I don't think using declarations care about public/private since they inherit that from the base class.

**Comment by ufleisch** [comment]
You are right, that standard (ISO/IEC 14882:2020(E), 9.9 The using declaration, 19) says

> A synonym created by a using-declaration has the usual accessibility for a member-declaration. A using-declarator that names a constructor does not create a synonym; instead, the additional constructors are accessible if they would be accessible when used to construct an object of the corresponding base class, and the accessibility of the using-declaration is ignored.

But I would consider it more readable if these `using`-declarations would be under the `public:` accessibility to make it clear.

**Comment by neheb** [comment]
Fixed.

**Pull request merged**
