### PR TITLE
tests: fix compilation on MSYS2

### PR DESCRIPTION
**Pull request by neheb**
Something about a deleted operator<<.

### CODE REVIEW

**Comment by sbooth** [comment]
Could you post the compiler error message?

**Comment by neheb** [comment]
‘’’
2023-08-01T22:27:08.9308241Z D:/a/_temp/msys64/clang64/include/cppunit/tools/StringHelper.h:25:9: error: overload resolution selected deleted operator '<<'
2023-08-01T22:27:08.9308867Z     ost << x;
2023-08-01T22:27:08.9309311Z     ~~~ ^  ~
2023-08-01T22:27:08.9310451Z D:/a/_temp/msys64/clang64/include/cppunit/TestAssert.h:74:42: note: in instantiation of function template specialization 'CppUnit::StringHelper::toString<wchar_t>' requested here
2023-08-01T22:27:08.9311213Z         return CPPUNIT_NS::StringHelper::toString(x);
2023-08-01T22:27:08.9311733Z                                          ^
2023-08-01T22:27:08.9312622Z D:/a/_temp/msys64/clang64/include/cppunit/TestAssert.h:168:50: note: in instantiation of member function 'CppUnit::assertion_traits<wchar_t>::toString' requested here
2023-08-01T22:27:08.9313382Z     Asserter::failNotEqual( assertion_traits<T>::toString(expected),
2023-08-01T22:27:08.9313940Z                                                  ^
2023-08-01T22:27:08.9314820Z ../tests/test_string.cpp:336:5: note: in instantiation of function template specialization 'CppUnit::assertEquals<wchar_t>' requested here
2023-08-01T22:27:08.9315616Z     CPPUNIT_ASSERT_EQUAL(L't', *it1);
2023-08-01T22:27:08.9316092Z     ^
2023-08-01T22:27:08.9316873Z D:/a/_temp/msys64/clang64/include/cppunit/TestAssert.h:333:17: note: expanded from macro 'CPPUNIT_ASSERT_EQUAL'
2023-08-01T22:27:08.9317603Z   ( CPPUNIT_NS::assertEquals( (expected),              \
2023-08-01T22:27:08.9318028Z                 ^
2023-08-01T22:27:08.9318586Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1137:31: note: candidate function [with _Traits = std::char_traits<char>] has been explicitly deleted
2023-08-01T22:27:08.9319231Z basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>&, wchar_t) = delete;
2023-08-01T22:27:08.9319707Z                               ^
2023-08-01T22:27:08.9320172Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:236:20: note: candidate function
2023-08-01T22:27:08.9320656Z     basic_ostream& operator<<(int __n);
2023-08-01T22:27:08.9321003Z                    ^
2023-08-01T22:27:08.9321469Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:233:20: note: candidate function
2023-08-01T22:27:08.9321948Z     basic_ostream& operator<<(bool __n);
2023-08-01T22:27:08.9322341Z                    ^
2023-08-01T22:27:08.9322795Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:234:20: note: candidate function
2023-08-01T22:27:08.9323278Z     basic_ostream& operator<<(short __n);
2023-08-01T22:27:08.9323628Z                    ^
2023-08-01T22:27:08.9324077Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:235:20: note: candidate function
2023-08-01T22:27:08.9324573Z     basic_ostream& operator<<(unsigned short __n);
2023-08-01T22:27:08.9324984Z                    ^
2023-08-01T22:27:08.9325641Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:237:20: note: candidate function
2023-08-01T22:27:08.9326128Z     basic_ostream& operator<<(unsigned int __n);
2023-08-01T22:27:08.9326528Z                    ^
2023-08-01T22:27:08.9326933Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:238:20: note: candidate function
2023-08-01T22:27:08.9327530Z     basic_ostream& operator<<(long __n);
2023-08-01T22:27:08.9327925Z                    ^
2023-08-01T22:27:08.9328377Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:239:20: note: candidate function
2023-08-01T22:27:08.9328877Z     basic_ostream& operator<<(unsigned long __n);
2023-08-01T22:27:08.9329286Z                    ^
2023-08-01T22:27:08.9329734Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:240:20: note: candidate function
2023-08-01T22:27:08.9330179Z     basic_ostream& operator<<(long long __n);
2023-08-01T22:27:08.9330575Z                    ^
2023-08-01T22:27:08.9331005Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:241:20: note: candidate function
2023-08-01T22:27:08.9331559Z     basic_ostream& operator<<(unsigned long long __n);
2023-08-01T22:27:08.9331941Z                    ^
2023-08-01T22:27:08.9332440Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:242:20: note: candidate function
2023-08-01T22:27:08.9333044Z     basic_ostream& operator<<(float __f);
2023-08-01T22:27:08.9333443Z                    ^
2023-08-01T22:27:08.9333889Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:243:20: note: candidate function
2023-08-01T22:27:08.9334409Z     basic_ostream& operator<<(double __f);
2023-08-01T22:27:08.9334804Z                    ^
2023-08-01T22:27:08.9335209Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:244:20: note: candidate function
2023-08-01T22:27:08.9335692Z     basic_ostream& operator<<(long double __f);
2023-08-01T22:27:08.9336094Z                    ^
2023-08-01T22:27:08.9336614Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:825:1: note: candidate function [with _Traits = std::char_traits<char>]
2023-08-01T22:27:08.9337178Z operator<<(basic_ostream<char, _Traits>& __os, char __c)
2023-08-01T22:27:08.9337581Z ^
2023-08-01T22:27:08.9338102Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:792:1: note: candidate function [with _CharT = char, _Traits = std::char_traits<char>]
2023-08-01T22:27:08.9338685Z operator<<(basic_ostream<_CharT, _Traits>& __os, char __cn)
2023-08-01T22:27:08.9339051Z ^
2023-08-01T22:27:08.9339549Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:832:1: note: candidate function [with _Traits = std::char_traits<char>]
2023-08-01T22:27:08.9340115Z operator<<(basic_ostream<char, _Traits>& __os, signed char __c)
2023-08-01T22:27:08.9340524Z ^
2023-08-01T22:27:08.9341006Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:839:1: note: candidate function [with _Traits = std::char_traits<char>]
2023-08-01T22:27:08.9341552Z operator<<(basic_ostream<char, _Traits>& __os, unsigned char __c)
2023-08-01T22:27:08.9341922Z ^
2023-08-01T22:27:08.9342405Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1158:31: note: candidate function [with _Traits = std::char_traits<char>] has been explicitly deleted
2023-08-01T22:27:08.9343014Z basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>&, char8_t) = delete;
2023-08-01T22:27:08.9343445Z                               ^
2023-08-01T22:27:08.9343987Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1171:31: note: candidate function [with _Traits = std::char_traits<char>] has been explicitly deleted
2023-08-01T22:27:08.9344617Z basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>&, char16_t) = delete;
2023-08-01T22:27:08.9345072Z                               ^
2023-08-01T22:27:08.9345609Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1174:31: note: candidate function [with _Traits = std::char_traits<char>] has been explicitly deleted
2023-08-01T22:27:08.9346212Z basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>&, char32_t) = delete;
2023-08-01T22:27:08.9346843Z                               ^
2023-08-01T22:27:08.9347293Z ../taglib/toolkit/tbytevector.h:610:29: note: candidate function
2023-08-01T22:27:08.9347797Z TAGLIB_EXPORT std::ostream &operator<<(std::ostream &s, const TagLib::ByteVector &v);
2023-08-01T22:27:08.9348266Z                             ^
2023-08-01T22:27:08.9348709Z ../taglib/toolkit/tstring.h:546:29: note: candidate function
2023-08-01T22:27:08.9349250Z TAGLIB_EXPORT std::ostream &operator<<(std::ostream &s, const TagLib::String &str);
2023-08-01T22:27:08.9349693Z                             ^
2023-08-01T22:27:08.9350639Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1140:31: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const wchar_t *' for 2nd argument; take the address of the argument with &
2023-08-01T22:27:08.9351373Z basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>&, const wchar_t*) = delete;
2023-08-01T22:27:08.9351897Z                               ^
2023-08-01T22:27:08.9352665Z D:/a/_temp/msys64/clang64/include/c++/v1/cstddef:125:3: note: candidate function template not viable: no known conversion from 'OStringStream' (aka 'basic_ostringstream<char>') to 'byte' for 1st argument
2023-08-01T22:27:08.9353326Z   operator<< (byte  __lhs, _Integer __shift) noexcept
2023-08-01T22:27:08.9353726Z   ^
2023-08-01T22:27:08.9354590Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:853:1: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const char *' for 2nd argument
2023-08-01T22:27:08.9355242Z operator<<(basic_ostream<_CharT, _Traits>& __os, const char* __strn)
2023-08-01T22:27:08.9355668Z ^
2023-08-01T22:27:08.9356378Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:899:1: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const char *' for 2nd argument
2023-08-01T22:27:08.9357009Z operator<<(basic_ostream<char, _Traits>& __os, const char* __str)
2023-08-01T22:27:08.9357424Z ^
2023-08-01T22:27:08.9371671Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:906:1: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const signed char *' for 2nd argument
2023-08-01T22:27:08.9372455Z operator<<(basic_ostream<char, _Traits>& __os, const signed char* __str)
2023-08-01T22:27:08.9373521Z ^
2023-08-01T22:27:08.9376107Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:914:1: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const unsigned char *' for 2nd argument
2023-08-01T22:27:08.9376877Z operator<<(basic_ostream<char, _Traits>& __os, const unsigned char* __str)
2023-08-01T22:27:08.9377323Z ^
2023-08-01T22:27:08.9378099Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1099:1: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const error_code' for 2nd argument
2023-08-01T22:27:08.9378750Z operator<<(basic_ostream<_CharT, _Traits>& __os, const error_code& __ec)
2023-08-01T22:27:08.9379155Z ^
2023-08-01T22:27:08.9379864Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1164:31: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const char8_t *' for 2nd argument
2023-08-01T22:27:08.9380537Z basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>&, const char8_t*) = delete;
2023-08-01T22:27:08.9381006Z                               ^
2023-08-01T22:27:08.9381784Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1177:31: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const char16_t *' for 2nd argument
2023-08-01T22:27:08.9382483Z basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>&, const char16_t*) = delete;
2023-08-01T22:27:08.9382943Z                               ^
2023-08-01T22:27:08.9383684Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1180:31: note: candidate function template not viable: no known conversion from 'const wchar_t' to 'const char32_t *' for 2nd argument
2023-08-01T22:27:08.9384600Z basic_ostream<char, _Traits>& operator<<(basic_ostream<char, _Traits>&, const char32_t*) = delete;
2023-08-01T22:27:08.9385016Z                               ^
2023-08-01T22:27:08.9385755Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:785:1: note: candidate template ignored: deduced conflicting types for parameter '_CharT' ('char' vs. 'wchar_t')
2023-08-01T22:27:08.9386384Z operator<<(basic_ostream<_CharT, _Traits>& __os, _CharT __c)
2023-08-01T22:27:08.9386794Z ^
2023-08-01T22:27:08.9387570Z D:/a/_temp/msys64/clang64/include/c++/v1/__random/uniform_int_distribution.h:258:1: note: candidate template ignored: could not match 'const uniform_int_distribution<_IT>' against 'const wchar_t'
2023-08-01T22:27:08.9388216Z operator<<(basic_ostream<_CharT, _Traits>& __os,
2023-08-01T22:27:08.9388614Z ^
2023-08-01T22:27:08.9389264Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:846:1: note: candidate template ignored: could not match 'const _CharT *' against 'wchar_t'
2023-08-01T22:27:08.9389831Z operator<<(basic_ostream<_CharT, _Traits>& __os, const _CharT* __str)
2023-08-01T22:27:08.9390233Z ^
2023-08-01T22:27:08.9390960Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1082:1: note: candidate template ignored: could not match 'const basic_string<_CharT, _Traits, _Allocator>' against 'const wchar_t'
2023-08-01T22:27:08.9391701Z operator<<(basic_ostream<_CharT, _Traits>& __os,
2023-08-01T22:27:08.9392110Z ^
2023-08-01T22:27:08.9392802Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1090:1: note: candidate template ignored: could not match 'basic_string_view<_CharT, _Traits>' against 'wchar_t'
2023-08-01T22:27:08.9393396Z operator<<(basic_ostream<_CharT, _Traits>& __os,
2023-08-01T22:27:08.9393787Z ^
2023-08-01T22:27:08.9394449Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1107:1: note: candidate template ignored: could not match 'const shared_ptr<_Yp>' against 'const wchar_t'
2023-08-01T22:27:08.9395076Z operator<<(basic_ostream<_CharT, _Traits>& __os, shared_ptr<_Yp> const& __p)
2023-08-01T22:27:08.9395520Z ^
2023-08-01T22:27:08.9396188Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1126:1: note: candidate template ignored: could not match 'const bitset<_Size>' against 'const wchar_t'
2023-08-01T22:27:08.9396812Z operator<<(basic_ostream<_CharT, _Traits>& __os, const bitset<_Size>& __x)
2023-08-01T22:27:08.9397252Z ^
2023-08-01T22:27:08.9398160Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1074:11: note: candidate template ignored: requirement 'integral_constant<bool, false>::value' was not satisfied [with _Stream = OStringStream &, _Tp = wchar_t]
2023-08-01T22:27:08.9398832Z _Stream&& operator<<(_Stream&& __os, const _Tp& __x)
2023-08-01T22:27:08.9399197Z           ^
2023-08-01T22:27:08.9399895Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1119:1: note: candidate template ignored: could not match 'const unique_ptr<_Yp, _Dp>' against 'const wchar_t'
2023-08-01T22:27:08.9400568Z operator<<(basic_ostream<_CharT, _Traits>& __os, unique_ptr<_Yp, _Dp> const& __p)
2023-08-01T22:27:08.9401021Z ^
2023-08-01T22:27:08.9401717Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1143:34: note: candidate template ignored: could not match 'basic_ostream' against 'basic_ostringstream'
2023-08-01T22:27:08.9402367Z basic_ostream<wchar_t, _Traits>& operator<<(basic_ostream<wchar_t, _Traits>&, char16_t) = delete;
2023-08-01T22:27:08.9405141Z                                  ^
2023-08-01T22:27:08.9406018Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1146:34: note: candidate template ignored: could not match 'basic_ostream' against 'basic_ostringstream'
2023-08-01T22:27:08.9406654Z basic_ostream<wchar_t, _Traits>& operator<<(basic_ostream<wchar_t, _Traits>&, char32_t) = delete;
2023-08-01T22:27:08.9407129Z                                  ^
2023-08-01T22:27:08.9407822Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1149:34: note: candidate template ignored: could not match 'basic_ostream' against 'basic_ostringstream'
2023-08-01T22:27:08.9408606Z basic_ostream<wchar_t, _Traits>& operator<<(basic_ostream<wchar_t, _Traits>&, const char16_t*) = delete;
2023-08-01T22:27:08.9409084Z                                  ^
2023-08-01T22:27:08.9409791Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1152:34: note: candidate template ignored: could not match 'basic_ostream' against 'basic_ostringstream'
2023-08-01T22:27:08.9410468Z basic_ostream<wchar_t, _Traits>& operator<<(basic_ostream<wchar_t, _Traits>&, const char32_t*) = delete;
2023-08-01T22:27:08.9410940Z                                  ^
2023-08-01T22:27:08.9411614Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1161:34: note: candidate template ignored: could not match 'basic_ostream' against 'basic_ostringstream'
2023-08-01T22:27:08.9412253Z basic_ostream<wchar_t, _Traits>& operator<<(basic_ostream<wchar_t, _Traits>&, char8_t) = delete;
2023-08-01T22:27:08.9412716Z                                  ^
2023-08-01T22:27:08.9413366Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:1167:34: note: candidate template ignored: could not match 'basic_ostream' against 'basic_ostringstream'
2023-08-01T22:27:08.9414037Z basic_ostream<wchar_t, _Traits>& operator<<(basic_ostream<wchar_t, _Traits>&, const char8_t*) = delete;
2023-08-01T22:27:08.9414504Z                                  ^
2023-08-01T22:27:08.9415322Z D:/a/_temp/msys64/clang64/include/c++/v1/iomanip:362:1: note: candidate template ignored: could not match 'const __iom_t8<_MoneyT>' against 'const wchar_t'
2023-08-01T22:27:08.9415965Z operator<<(basic_ostream<_CharT, _Traits>& __os, const __iom_t8<_MoneyT>& __x)
2023-08-01T22:27:08.9416399Z ^
2023-08-01T22:27:08.9417045Z D:/a/_temp/msys64/clang64/include/c++/v1/iomanip:482:1: note: candidate template ignored: could not match 'const __iom_t10<_CharT>' against 'const wchar_t'
2023-08-01T22:27:08.9417670Z operator<<(basic_ostream<_CharT, _Traits>& __os, const __iom_t10<_CharT>& __x)
2023-08-01T22:27:08.9418108Z ^
2023-08-01T22:27:08.9418785Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:221:20: note: candidate function not viable: no known conversion from 'const wchar_t' to 'ostream &(*)(ostream &)' for 1st argument
2023-08-01T22:27:08.9419430Z     basic_ostream& operator<<(basic_ostream& (*__pf)(basic_ostream&))
2023-08-01T22:27:08.9419852Z                    ^
2023-08-01T22:27:08.9420980Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:225:20: note: candidate function not viable: no known conversion from 'const wchar_t' to 'basic_ios<char_type, traits_type> &(*)(basic_ios<char_type, traits_type> &)' (aka 'basic_ios<char, std::char_traits<char>> &(*)(basic_ios<char, std::char_traits<char>> &)') for 1st argument
2023-08-01T22:27:08.9421794Z     basic_ostream& operator<<(basic_ios<char_type, traits_type>&
2023-08-01T22:27:08.9422260Z                    ^
2023-08-01T22:27:08.9423058Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:230:20: note: candidate function not viable: no known conversion from 'const wchar_t' to 'ios_base &(*)(ios_base &)' for 1st argument
2023-08-01T22:27:08.9423695Z     basic_ostream& operator<<(ios_base& (*__pf)(ios_base&))
2023-08-01T22:27:08.9424107Z                    ^
2023-08-01T22:27:08.9424885Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:245:20: note: candidate function not viable: no known conversion from 'const wchar_t' to 'const void *' for 1st argument; take the address of the argument with &
2023-08-01T22:27:08.9425512Z     basic_ostream& operator<<(const void* __p);
2023-08-01T22:27:08.9425867Z                    ^
2023-08-01T22:27:08.9426826Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:254:20: note: candidate function not viable: no known conversion from 'const wchar_t' to 'basic_streambuf<char_type, traits_type> *' (aka 'basic_streambuf<char, std::char_traits<char>> *') for 1st argument
2023-08-01T22:27:08.9427558Z     basic_ostream& operator<<(basic_streambuf<char_type, traits_type>* __sb);
2023-08-01T22:27:08.9427902Z 
2023-08-01T22:27:08.9428080Z                    ^
2023-08-01T22:27:08.9428337Z 
2023-08-01T22:27:08.9429145Z D:/a/_temp/msys64/clang64/include/c++/v1/ostream:260:20: note: candidate function not viable: no known conversion from 'const wchar_t' to 'nullptr_t' (aka 'std::nullptr_t') for 1st argument
2023-08-01T22:27:08.9429591Z 
2023-08-01T22:27:08.9429826Z     basic_ostream& operator<<(nullptr_t)
2023-08-01T22:27:08.9430101Z 
2023-08-01T22:27:08.9430296Z                    ^
2023-08-01T22:27:08.9430550Z 
2023-08-01T22:27:08.9430760Z 1 error generated.
‘’’

**Comment by ufleisch** [comment]
This is probably a problem with your environment, maybe a mismatch of MSYS2 environments. I have successfully built TagLib with MSYS2 using the following procedure.

* msys2 installed from https://www.msys2.org/
* `pacman -Suy`
* Start MSYS CLANG64 Shell
   Install dependencies and build dependencies according to
   https://packages.msys2.org/package/mingw-w64-clang-x86_64-taglib?repo=clang64
   ```
   pacman -S mingw-w64-clang-x86_64-gcc-libs mingw-w64-clang-x86_64-zlib mingw-w64-clang-x86_64-cc \
     mingw-w64-clang-x86_64-cmake mingw-w64-clang-x86_64-cppunit mingw-w64-clang-x86_64-ninja
   ```
* Build TagLib and run the tests (in a build directory on the same level as the *taglib* source directory)
   ```
   cmake -GNinja -DBUILD_SHARED_LIBS=ON -DBUILD_BINDINGS=ON -DBUILD_EXAMPLES=ON ../taglib
   ninja
   PATH=$PATH:/clang64/bin:./taglib tests/test_runner
   ```

**Comment by neheb** [comment]
github CI: https://github.com/neheb/taglib/actions/runs/6067584517/job/16459443707

**Comment by neheb** [comment]
https://github.com/taglib/taglib/pull/1124 does not have this issue but has a different one...

**Comment by neheb** [comment]
@ufleisch same compilation error also happens on FreeBSD.

**Comment by neheb** [comment]
I think the issue comes out when taglib is compiled as C++20. Note how where are deleted: https://en.cppreference.com/w/cpp/io/basic_ostream/operator_ltlt2

**Pull request merged**
