### PR TITLE
Adds a unified picture interface

### PR DESCRIPTION
**Pull request by MaxLeb**

### CODE REVIEW

**Comment by gogglesguy** [comment]
I assume this would be a 2.0 feature. Perhaps project maintainers can add a 2.0 github label...

**Comment by supermihi** [comment]
Doesn't look bad to me on a first glance! If I find the time I'll review your patch more deeply next week. Not sure if I've got the C++ skills to decide on the quality alone, bus as I've contributed the PropertyMap interface, I might at least be able to spot some problems etc. ...

**Comment by MaxLeb** [comment]
Thanks. If there are any issues with it let me know i'll try to fix it asap.

**Comment by supermihi** [comment]
Sure, and sorry for the long delays. ;-) As @gogglesguy said, however, we can't include this patch before taglib-2.0 because of binary compatibility, so you might have to be patient.

**Comment by TsudaKageyu** [comment]
We have a special branch named ```taglib2``` to make binary incompatible changes.

@MaxLeb, you can start working on ```taglib2``` branch right now. Or you have to make an ugly workaround with ```dynamic_cast``` to avoid adding virtual functions (like I did in #506) if you want to make your patches compatible with TagLib 1.x.

**Comment by MaxLeb** [comment]
I will then rebase on taglib2, I don't want to have ugly workaround.

**Comment by supermihi** [comment]
Great. As it might take some time to get your patch included, such a workaround probably would not be worth the effort anyway.

**Comment by MaxLeb** [comment]
However I don't see where this workaround would apply

**Comment by MaxLeb** [comment]
Sorry for not doing anything yet but i am quite busy with work.
I am doing the rebase today.

**Pull request closed without merging**
