### PR TITLE
Improve speed of metadata track tag search for contemporary x86/64 CPUs

### PR DESCRIPTION
**Pull request by shaforostoff**
use AVX2

### CODE REVIEW

**Comment by scotchi** [comment]
Hi Nick -- have you benchmarked this with disk caches cleared?  These sorts of things are almost always I/O bound, and this introduces a lot of complexity for something I'm skeptical is faster for real-world use cases.  (I haven't tried this since SSDs became common, so there's a chance that some things which used to be I/O-bound are now CPU bound.)

**Comment by scotchi** [comment]
After trying this on my Linux box (CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz) I'm not seeing any significant improvement in cached or non-cached performance for scanning a directory of 13 GB of MP3s.  I'd really need to see a use case where this significantly improves non-cached performance to consider merging it.  (There are a number of issues in the patch itself, but for the moment my primary concern is seeing this improve an important metric.)

**Comment by scotchi** [comment]
Also worth noting there is that in my tests (on an SSD) it was also pretty clear that things are still I/O bound:  in non-cached test a single core only hit 42% usage and the non-cached version took 7 times longer.

**Comment by shaforostoff** [comment]
> After trying this on my Linux box (CPU: Intel(R) Core(TM) i5-2500K CPU @ 3.30GHz) I'm not seeing any significant improvement
of course you won't see it, since your CPU is only 2nd gen (2500K), whereas avx instructions are available only starting with 4th gen

**Comment by scotchi** [comment]
That's the sort of info that should really be included in a pull request:

- These are the CPUs this affects
- These are the use cases that it improves
- These are the benchmarks proving such

It's just random chance that I had a little time to test this out -- most of the time a patch like this wouldn't even get reviewed since there's not enough info to evaluate it on.

**Comment by scotchi** [comment]
There's also no measurable performance increase in scanning 83 GB of MP3s on a brand new Macbook Pro (MacBookPro16,2 / Quad-Core Intel Core i7).  Again, for this to be given serious consideration, there needs to be a repeatable benchmark included that demonstrates improved non-cached performance.

**Pull request closed without merging**
