### PR TITLE
Add DSF and DSDIFF file types management

### PR DESCRIPTION
**Pull request by jonaski**
Resuming PR from @damien78
I have merged with master and fixed the conflicts
I also added DSF and DSDIFF to detectByExtension

### CODE REVIEW

**Comment by sbooth** [comment]
I'd like to merge this PR for the next release but right now the `TestFileRef::testDSF` and `TestFileRef::testDSDIFF` tests are failing. I will take a look later today at what the cause might be.

**Comment by jonaski** [comment]
Thanks!

**Comment by sbooth** [comment]
I figured out what the problem is. It appears the test data files are malformed so the tests were behaving correctly.

However, I did add `isSupported` to both `DSF::File` and `DSDIFF::File`. If you give me write access to your PR I will push the changes.

**Comment by sbooth** [comment]
The test files aren't malformed after all; I'll continue to investigate.

**Comment by sbooth** [comment]
@scotchi Is there a project preference for merging PRs using a merge commit or squash and merge?

**Comment by scotchi** [comment]
@sbooth Unfortunately, going through the code, this one wasn't ready to be merged yet.  There's for example an unimplemented `save()` method, no `TagTypes` enum, no ID3v2 version selection support, no `strip()` method, and a lot of style issues.  I'm going through now seeing if I can get it in shape such that it can go in the next release, but in a pinch, I may pull it before the release.

**Comment by sbooth** [comment]
This was a large PR, apologies for missing a few things.

**Comment by scotchi** [comment]
Unfortunately, this changeset is pretty far away from being ready for master.  I'm at more than 400 lines of changes now just trying to get it to implement the rest of the standard `File` API, and I haven't even started on cleaning up style issues.  Tests for basic stuff like writing to the newly introduced tag type fail and so forth.  Once I've got things in a pushable state, I'll push into a separate branch and remove these classes from master so that they don't block a new release.  If they're in a better state by the next release, then they can go be merged back.

**Pull request merged**
