### PR TITLE
clang-tidy fixes

### PR DESCRIPTION
**Pull request by neheb**

### CODE REVIEW

**Comment by scotchi** [comment]
TagLib doesn't use C++11, which most of these "fixes" assume.

**Comment by scotchi** [comment]
To be clear, even most of the non-C++11 changes I wouldn't commit.  There's no reason to mess up the git history for changes that don't actually improve the code in any meaningful way.

**Comment by neheb** [comment]
Oh I sent the wrong branch. Will post the right one.

**Comment by neheb** [comment]
@scotchi compiling with -std=c++98 fails:

```
  5%] Building CXX object taglib/CMakeFiles/tag.dir/toolkit/trefcounter.cpp.o
In file included from /usr/include/c++/8/atomic:38,
                 from /home/mangix/devstuff/taglib/taglib/toolkit/trefcounter.cpp:33:
/usr/include/c++/8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support \
```

**Pull request closed without merging**
